apiVersion: v1
kind: Service
metadata:
  name: camouflage-srv
spec:
  type: LoadBalancer
  selector:
    app: camouflage
  ports:
    - name: metrics-port
      port: 5555
      targetPort: 5555
    - name: http-port
      port: 8080
      targetPort: 8080
    - name: https-port
      port: 8443
      targetPort: 8443
    - name: http2-port
      port: 8081
      targetPort: 8081
    - name: ws-port
      port: 8082
      targetPort: 8082
    - name: grpc-port
      port: 4312
      targetPort: 4312
